// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl1-q1ScKvDl9sL7ZhQ__4evPGBdYrlkQ',
    appId: '1:947423295138:web:34457795a0919f1460c9fb',
    messagingSenderId: '947423295138',
    projectId: 'flutterquizapp-4ff98',
    authDomain: 'flutterquizapp-4ff98.firebaseapp.com',
    storageBucket: 'flutterquizapp-4ff98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGy9fTiLXobK5a9ioBsUIfgOuGiQZgtiM',
    appId: '1:947423295138:android:e62176f5fb7c7ba960c9fb',
    messagingSenderId: '947423295138',
    projectId: 'flutterquizapp-4ff98',
    storageBucket: 'flutterquizapp-4ff98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSAiQg2jLlna2XE792NpR3Hcwy3A9Qn2I',
    appId: '1:947423295138:ios:8a207d7ecff1821660c9fb',
    messagingSenderId: '947423295138',
    projectId: 'flutterquizapp-4ff98',
    storageBucket: 'flutterquizapp-4ff98.appspot.com',
    iosClientId: '947423295138-b3a78geuocl8s48rpc50pss6ultcbor4.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSAiQg2jLlna2XE792NpR3Hcwy3A9Qn2I',
    appId: '1:947423295138:ios:a2dd1e4e6eae5f3d60c9fb',
    messagingSenderId: '947423295138',
    projectId: 'flutterquizapp-4ff98',
    storageBucket: 'flutterquizapp-4ff98.appspot.com',
    iosClientId: '947423295138-tv8u1lgkbjts42hs4ljbndrlcjmj8llm.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
